mode: ContinuousDeployment

branches: 
  dev:
    mode: ContinuousDeployment
    tag: Alpha
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false

  features?[/-]:
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false